{% set name = "gpuci-ccache" %}
{% set version = "4.2.0dev0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/ccache/ccache.git
  git_rev: 12ecd73fcd8aa7024d5851c1738223b8aff0c6e9
  patches: patch_test_suite.patch  # [osx]

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make
    - cmake
  host:
    - zlib
    - xz
  run:
    - zlib

test:
  commands:
    - ccache --help
    - ccache --version

about:
  home: https://ccache.samba.org/
  license: GPL-3.0-only
  license_family: GPL
  license_file: GPL-3.0.txt
  summary: A compiler cache

  description: |
    ccache is a compiler cache. It speeds up recompilation by caching
    previous compilations and detecting when the same compilation is
    being done again. Supported languages are C, C++, Objective-C and Objective-C++.
  doc_url: https://ccache.samba.org/manual.html
  dev_url: https://github.com/ccache/ccache

extra:
  recipe-maintainers:
    - edisongustavo
    - marcelotrevisani
